# Generated by Django 3.2.6 on 2021-12-31 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterScraper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
    ]
