# Generated by Django 3.2.6 on 2022-01-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterScraper', '0003_alter_tweet_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
    ]
